#!/usr/bin/with-contenv bash

# install app
[[ ! -d /app/sickrage/.git ]] && \
	git clone --depth 1 https://github.com/SickRage/SickRage.git /app/sickrage

# permissions
chown -R abc:abc \
	/app \
	/config
