#!/usr/bin/with-contenv bash

# install app
[[ ! -d /app/sickrage/.git ]] && \
	git clone https://git.sickrage.ca/SiCKRAGE/sickrage.git /app/sickrage && pip install -r /app/sickrage/requirements.txt

# permissions
chown -R abc:abc \
	/app \
	/config
